<a href="https://colab.research.google.com/github/JingruGong1023/Machine_Learning/blob/main/Data_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This file includes some review and practice of basic python data manipulation functions and libraries


In [4]:
#String format

s = "{} is handsome, but {} is not"
print(s.format('Rayman','Jason'))
s = "{name1} is handsome, but {name2} is not}" #works ths same

name1 = 'Bob'
name2 = 'Jade'
s = f" {name1} is handsome, but {name2} is not"
print(s )

Rayman is handsome, but Jason is not
 Bob is handsome, but Jade is not


**LISTS** </br>
In Python, lists are mutable

In [7]:
list1 = []

lst2 = [1,2,3,4]
lst3 = ['one', 2, 'three', 4] # create a list with different data type values
print(list1, lst2,lst3)
print(lst2+lst3) #list concatenation

[] [1, 2, 3, 4] ['one', 2, 'three', 4]
[1, 2, 3, 4, 'one', 2, 'three', 4]


In [11]:
lst = range(6) # create an list of numbers using built-in function range
print(type(lst)) # class 'range'
print(lst)

lst = list(lst) #change to list
print(lst)

print(lst[::2]) # change index step to 2, [0, 2, 4]
print(lst[::-1]) # reverse order, [5, 4, 3, 2, 1, 0], common usage
print(lst[:-1]) # negative index slicing, [0, 1, 2, 3, 4]
print(lst[-1:]) # negative index slicing, [5]

<class 'range'>
range(0, 6)
[0, 1, 2, 3, 4, 5]
[0, 2, 4]
[5, 4, 3, 2, 1, 0]


In [ ]:
ss = 'Hello World!' # initialize a string
print(ss)

print(ss[:]) # the whole list
print(ss[1:3]) # index from 1 to 2

# **Looping**

In [12]:
# basic loop
skills = ['ML', 'Stat', 'Coding', 'Business']
for skill in skills:
  print(skill)

ML
Stat
Coding
Business


In [15]:
#enumerate, bind index with list element

skills = ['ML', 'Stat', 'Coding', 'Business']

# check enumerate output
print(list(enumerate(skills)))

#change the start index
print(list(enumerate(skills, start =1)))

for idx, skill in enumerate(skills):
  print(idx, skill)

[(0, 'ML'), (1, 'Stat'), (2, 'Coding'), (3, 'Business')]
[(1, 'ML'), (2, 'Stat'), (3, 'Coding'), (4, 'Business')]
0 ML
1 Stat
2 Coding
3 Business


In [18]:
#List comprehension

nums = list(range(6))
print(nums)

lst = [x**2 for x in nums]
print(lst)


[0, 1, 2, 3, 4, 5]
[0, 1, 4, 9, 16, 25]


# **Tuple**

A tuple is an immutable ordered list of values.


In [26]:
t = (21,42,33)
print(t)
skills = ['ML', 'Stat', 'Coding', 'Business']
t_dict = {('data',idx): skill for idx, skill in enumerate(skills)}
print(t_dict)

(21, 42, 33)
{('data', 0): 'ML', ('data', 1): 'Stat', ('data', 2): 'Coding', ('data', 3): 'Business'}


# **Dictionary**

{key:value}

In [33]:
skills = ['ML', 'Stat', 'Coding', 'Business']
scores = [90, 80, 1, 59]

score_dict = {'ML': 90, 'Stat': 80, 'Coding': 1, 'Business': 59} # create a dictionary
print(score_dict['ML'])
print('Stat' in score_dict)

score_dict['Spark']=70

print("Current score: %d" %score_dict['Spark'])

score_dict.pop('Spark') #show and remove
print(score_dict)

90
True
Current score: 70
{'ML': 90, 'Stat': 80, 'Coding': 1, 'Business': 59}


In [34]:
# (Advanced)construct dictionary
{skills[i]:scores[i] for i in range(len(skills))}
dict(zip(skills, scores))

{'Business': 59, 'Coding': 1, 'ML': 90, 'Stat': 80}

In [35]:
#dictionary comprehension
#get a dictionary for range 6 ,if a number is even, square it
num_dict = {x:x**2 if x%2==0 else x for x in range(6)}
print(num_dict)

{0: 0, 1: 1, 2: 4, 3: 3, 4: 16, 5: 5}


In [36]:
# loop over dictionary
for skill,score in score_dict.items():
  print(skill,score)

ML 90
Stat 80
Coding 1
Business 59


# **SET**
a set is an unordered collection of **distinct** elements

In [39]:
skills = {'ML', 'Stat', 'Coding', 'Business'} #set
skills_list = ['ML', 'Stat', 'Coding', 'Business']

print(skills)
print('Business' in skills) # check if an element is in a set
print('Spark' in skills) # False

# set comprehension
nums = {num for num in range(6)}
print(type(nums)) # class 'set'

{'Stat', 'ML', 'Coding', 'Business'}
True
False
<class 'set'>


# **Numpy**

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance.

In [40]:
#@title import packages
import numpy as np #numpy
import pandas as pd #pandas

In [43]:
lst = [[1,2,3],[4,5,6]]
print(type(lst))
a = np.array(lst)
print(a)
print(a[0]) # first row
print(a[0][1]) # first row, second column
print(a.shape) # 2 x 3
print(a.ndim) # 2 dimensions
print(a.dtype) # data type of the elements of array
print(a.size) # total number of elements in the matrix

<class 'list'>
[[1 2 3]
 [4 5 6]]
[1 2 3]
2
(2, 3)
2
int64
6


In [49]:
# useful functions to create numpy array
b = np.arange(0, 10, 2, dtype='float') # create 1d array, [start, stop)
print(type(b)) # class 'numpy.ndarray'
print(b)
print(b.shape)

c = np.linspace(1.5, 2.5, 9) # create 1d array with float, [start, stop]
print(type(c)) # class 'numpy.ndarray'
print(c)
print(c.shape)

d = np.zeros((2, 3)) # all zeros
print(type(d)) # class 'numpy.ndarray'
print(d)

e = np.ones((2, 3)) # all ones
print(type(e)) # class 'numpy.ndarray'
print(e)

f = np.full((2, 3), 9) # constant matrix
print(type(f)) # class 'numpy.ndarray'
print(f)

g = np.eye(3) # 3 x 3 identity matrix
print(type(g)) # class 'numpy.ndarray'
print(g)

<class 'numpy.ndarray'>
[0. 2. 4. 6. 8.]
(5,)
<class 'numpy.ndarray'>
[1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5  ]
(9,)
<class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>
[[9 9 9]
 [9 9 9]]
<class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [52]:
h = b.reshape((5,1))
print(h)

# One shape dimension can be -1. 
# In this case, the value is inferred from the length of the array and remaining dimensions.
i = c.reshape((-1, 3))
print(i)
print(i.shape)

j = d.reshape((2, 3, 1))
print(j)
print(j.shape)

[[0.]
 [2.]
 [4.]
 [6.]
 [8.]]
[[1.5   1.625 1.75 ]
 [1.875 2.    2.125]
 [2.25  2.375 2.5  ]]
(3, 3)
[[[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]]
(2, 3, 1)


In [55]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

a.reshape((2,2,3)) #two list, two rows, 3 cols

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
# boolean masking
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

a_idx1 = (a < 5) # return the boolean array that satisfies the conidtion
print(a_idx1)
a_idx2 = (a >=5) & (a <= 10) # return the boolean array that satisfies the conidtion
print(a_idx2)

print(a[a_idx1]) # return the corresponding array which is true
print(a[a_idx2]) # return the corresponding array which is true

print(a[(a > 5) & (a < 10)]) # single statement

[[ True  True  True  True]
 [False False False False]
 [False False False False]]
[[False False False False]
 [ True  True  True  True]
 [ True  True False False]]
[1 2 3 4]
[ 5  6  7  8  9 10]
[6 7 8 9]


# MATH

In [57]:
import numpy as np

a = np.array([[10, 11, 12], [13, 14, 15]])
print(a.shape)
print(a)
b = np.arange(1, 7).reshape((2, 3))
print(b.shape)
print(b)

# element-wise calculation:
print(a + b)
print(a - b)
print(np.add(a, b))
print(a * b)

# Matrix product
print(np.dot(a, b.transpose())) # 2x3, 3x2
print(a.T.dot(b)) # 3x2, 2x3

(2, 3)
[[10 11 12]
 [13 14 15]]
(2, 3)
[[1 2 3]
 [4 5 6]]
[[11 13 15]
 [17 19 21]]
[[9 9 9]
 [9 9 9]]
[[11 13 15]
 [17 19 21]]
[[10 22 36]
 [52 70 90]]
[[ 68 167]
 [ 86 212]]
[[ 62  85 108]
 [ 67  92 117]
 [ 72  99 126]]


In [58]:
# matrix transpose 转置
b.T
b.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [59]:
print(np.sum(a, axis = 0)) # the column is fixed, sum along row for this column
print(np.sum(a, axis = 1)) # the row    is fixed, sum along column for this row

[23 25 27]
[33 42]


In [60]:
# (Advanced+)broadcasting

import numpy as np

a = np.array([[10, 11, 12], [13, 14, 15]]) # 2x3
print(a)

a += 1 # add 1 to all the elements # 1
print(a)

a += np.array([-1, -2, -3]) # add [-1, -2, -3] to all columns for each row # 3
print(a)

a += np.array([[-1], [-2]]) # add [[-1], [-2]] to all rows for each column 2x1
print(a)

[[10 11 12]
 [13 14 15]]
[[11 12 13]
 [14 15 16]]
[[10 10 10]
 [13 13 13]]
[[ 9  9  9]
 [11 11 11]]


In [63]:
import numpy as np

# Two dimensions are compatible when
# they are equal, or
# one of them is 1
a = np.array([1, 2, 3]) # 1x3
b = np.array([[4], [5], [6]]) # 3x1
print(np.add(a,b)) #add 4 to each value in a, add 5 to each value in a etc

[[5 6 7]
 [6 7 8]
 [7 8 9]]


# **RANDOM**

In [64]:
# generate random number
print(np.random.rand(2,2)) # Random numbers between [0,1) of shape 2,2

print(np.random.randn(2,2)) # Normal distribution with mean=0 and variance=1 of shape 2,2
print(np.random.randint(0, 10, size=[2,2])) # Random integers between [0, 10) of shape 2,2
print(np.random.random()) # One random number between [0,1)
print(np.random.random(size=[2,2])) # Random numbers between [0,1) of shape 2,2
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10)) # Pick 10 items from a given list, with equal probability
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.3, .1, 0.1, 0.4, 0.1])) # Pick 10 items from a given list with a predefined probability 'p'
print(np.random.choice(np.arange(100),size=[10,3],replace=True)) # get 10x3 random samples from [0-99] with replacement 

[[0.10669852 0.37141334]
 [0.24880894 0.68844553]]
[[-1.36748492  0.77586658]
 [ 2.59071177 -0.83144697]]
[[9 2]
 [0 9]]
0.37233830924843847
[[0.94359404 0.56418611]
 [0.26700376 0.67034439]]
['a' 'e' 'u' 'o' 'o' 'e' 'e' 'a' 'o' 'u']
['i' 'o' 'u' 'a' 'u' 'o' 'e' 'a' 'o' 'a']
[[78 91 53]
 [ 8 70  8]
 [50 87 16]
 [58 60 13]
 [24 46  8]
 [89 88 52]
 [40 91 53]
 [59 49 53]
 [97 11 99]
 [37 68 25]]


In [65]:
url="https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/d546eaee765268bf2f487608c537c05e22e4b221/iris.csv"
iris = pd.read_csv(url)

use random generator to do train/test split

In [67]:
print(iris.head())
print(iris.info())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [70]:
iris_index = np.arange(iris.shape[0])
print(iris_index)
num_training = int(np.floor(0.75*iris.shape[0]))
iris_training_index = np.random.choice(iris_index, size = num_training, replace=False)
irist_test_index = np.delete(iris_index,iris_training_index)

iris_train = iris.iloc[iris_training_index]
iris_test = iris.iloc[irist_test_index]

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149]


In [74]:
#use sklearn to split the data
from sklearn.model_selection import train_test_split

x = iris.drop('species',axis=1)
y = iris['species']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

print(x_train.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112 entries, 132 to 36
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  112 non-null    float64
 1   sepal_width   112 non-null    float64
 2   petal_length  112 non-null    float64
 3   petal_width   112 non-null    float64
dtypes: float64(4)
memory usage: 4.4 KB
None


# **Pandas**

**pandas** is a Python package providing fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real world data analysis in Python. Additionally, it has the broader goal of becoming **the most powerful and flexible open source data analysis / manipulation tool available in any language**. It is already well on its way toward this goal.

The two primary data structures of pandas, **Series (1-dimensional)** and **DataFrame (2-dimensional)**, handle the vast majority of typical use cases in finance, statistics, social science, and many areas of engineering. pandas is built on top of **NumPy** and is intended to integrate well within a scientific computing environment with many other 3rd party libraries.

In [79]:
import pandas as pd

iris = 'http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
df_iris = pd.read_csv(iris,sep=',',header=None) #don't take the first row as head

In [80]:
print(df_iris.head())

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa


In [82]:
# Read data from Google Drive (recommend)
# step 1: change your csv file in Drive as Anyone with the link can view
# https://drive.google.com/open?id=1800ai5EJIDftDTS8wdgalA4SVo40oufH

file_id='1AbJ1P9aXcjut9ox5lh6oDx4uYnLY2HBQ'
link='https://drive.google.com/uc?export=download&id={FILE_ID}'
csv_url=link.format(FILE_ID=file_id)

df_uk_rain = pd.read_csv(csv_url)

In [81]:
#save dataframe
df_iris.to_csv('df.csv',index = False)
from google.colab import files
files.download('df.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# **Data Structure**
**Series** is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). The axis labels are collectively referred to as the index.

**DataFrame** is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table, or a dict of Series objects. It is generally the most commonly used pandas object. 

In [ ]:
#series from list
